# toml 的语法 https://mojotv.cn/2018/12/26/what-is-toml

#下面是个表格语法
[versions]
kotlin_version = "1.5.30"
gradle_tools = "7.1.3"
target_sdk = "32"
compile_sdk = "32"
min_sdk = "14"
appcompat_version = "1.4.1"
version_code = "1"
version_name = "1.0"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
gradle_tools = { module = "com.android.tools.build:gradle", version.ref = "gradle_tools" }
kotlin_gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin_version" }
kotlin_stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin_version" }

